package org.javaacademy.wonderfield;

public enum Wheel {
    MOVE_SKIP,
    ONE_HUNDRED,
    TWO_HUNDRED,
    THREE_HUNDRED,
    FOUR_HUNDRED,
    FIVE_HUNDRED,
    SIX_HUNDRED,
    SEVEN_HUNDRED,
    EIGHT_HUNDRED,
    NINE_HUNDRED,
    ONE_THOUSAND,
    ONE_THOUSAND_ONE_HUNDRED,
    ONE_THOUSAND_TWO_HUNDRED,
    MULTIPLICATION

}
